[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Ativa as configurações de monitor serial
monitor_speed = 115200

; Configurações do OTA (Mantenha as suas)
upload_protocol = espota
upload_port = 192.168.1.100 ; Substitua pelo IP do seu ESP32

; ---> PARÂMETROS NOVOS (O Segredo da Memória) <---
; build_flags: Injeta comandos diretos no compilador C++
; -DBOARD_HAS_PSRAM: Diz ao núcleo do ESP32 que ele pode usar o chip de RAM externa
; -mfix-esp32-psram-cache-issue: Corrige um bug físico de silício em placas ESP32 mais antigas ao acessar a memória externa
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue